### ISSUE TITLE
[CORE API] getTeams() Fails with ApiResponseParsingException: No content to map due to end-of-input  at [Source: (String)""; line: 1, column: 0]

### ISSUE THREAD

**Issue by jlong23** [hkarthik7/azure-devops-java-sdk#70]
I seem to have an issue with coreapi.getTeams() service call that works from the raw Azure DevOps API service calls, but seems to be empty on the AzD service.

org.azd.exceptions.AzDException: ApiResponseParsingException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
	at org.azd.helpers.JsonMapper.mapJsonResponse(JsonMapper.java:59) ~[azd-5.0.10.jar:na]
	at org.azd.core.CoreApi.getTeams(CoreApi.java:357) ~[azd-5.0.10.jar:na]
	at io.noda.adaptor.azuredevops.domain.AzureAdaptor.getTeams(AzureAdaptor.java:91) ~[classes/:na]

When a raw service call is done at browser:
https://dev.azure.com/rabbitearsvideoproduction/_apis/teams?api-version=7.1-preview.3
{
    "value": [
        {
            "id": "553f1e11-ec5c-4ed3-81cb-71de6365e900",
            "name": "The-Mongooses",
            "url": "https://dev.azure.com/rabbitearsvideoproduction/_apis/projects/3a335c3a-bad0-4850-b46d-7942d45c239e/teams/553f1e11-ec5c-4ed3-81cb-71de6365e900",
            "description": "",
            "identityUrl": "https://spsprodcus5.vssps.visualstudio.com/Aff21754c-65bc-40f1-ae29-af385431d22a/_apis/Identities/553f1e11-ec5c-4ed3-81cb-71de6365e900",
            "projectName": "Noda-Integration-AzureDevOps-adaptor",
            "projectId": "3a335c3a-bad0-4850-b46d-7942d45c239e"
        },
        {
            "id": "91ddb058-fbfb-4a14-b61c-09f8e4d6f1b3",
            "name": "Noda-Integration-AzureDevOps Team",
            "url": "https://dev.azure.com/rabbitearsvideoproduction/_apis/projects/4fcfd2af-a1da-44ee-bd48-ef80f837ae7d/teams/91ddb058-fbfb-4a14-b61c-09f8e4d6f1b3",
            "description": "The default project team.",
            "identityUrl": "https://spsprodcus5.vssps.visualstudio.com/Aff21754c-65bc-40f1-ae29-af385431d22a/_apis/Identities/91ddb058-fbfb-4a14-b61c-09f8e4d6f1b3",
            "projectName": "Noda-Integration-AzureDevOps",
            "projectId": "4fcfd2af-a1da-44ee-bd48-ef80f837ae7d"
        },
        {
            "id": "dad01d92-2ae8-4824-9b2b-1cf4049268ae",
            "name": "Noda-Integration-AzureDevOps-adaptor-TeamA",
            "url": "https://dev.azure.com/rabbitearsvideoproduction/_apis/projects/3a335c3a-bad0-4850-b46d-7942d45c239e/teams/dad01d92-2ae8-4824-9b2b-1cf4049268ae",
            "description": "The default project team.",
            "identityUrl": "https://spsprodcus5.vssps.visualstudio.com/Aff21754c-65bc-40f1-ae29-af385431d22a/_apis/Identities/dad01d92-2ae8-4824-9b2b-1cf4049268ae",
            "projectName": "Noda-Integration-AzureDevOps-adaptor",
            "projectId": "3a335c3a-bad0-4850-b46d-7942d45c239e"
        }
    ],
    "count": 3
}

All other service calls seem to be working for me, so I am not completely sure it's PaT authority, but from the code, It looks like it checks for that.

Also there seems to be a data type miss-match with the type on the 4 element Teams Get Call 

https://learn.microsoft.com/en-us/rest/api/azure/devops/core/teams/get-all-teams?view=azure-devops-rest-7.1&tabs=HTTP
$mine is boolean on MS Azure DevOps API and is string in the AzD library

**Comment by hkarthik7** [comment]
Hiya @jlong23, Let me take a look and get back to you on this. And yes, the typs of `$mine` query parameter is wrong, I will make changes and push it in next version release.

```java
Teams getTeams(boolean expandIdentity, String mine, int skip, int top) throws AzDException
```

**Comment by jlong23** [comment]
2023-10-27T02:59:22.838-05:00  INFO 3131401 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2023-10-27T02:59:23.288-05:00  INFO 3131401 --- [ient-2-Worker-0] jdk.httpclient.HttpClient                : REQUEST: https://dev.azure.com/rabbitearsvideoproduction/_apis/resourceAreas/79134c72-4a58-4b42-976c-04e7115f32bf?api-preview=5.0-preview.1 GET
2023-10-27T02:59:23.414-05:00  INFO 3131401 --- [ient-2-Worker-0] jdk.httpclient.HttpClient                : RESPONSE: (GET https://dev.azure.com/rabbitearsvideoproduction/_apis/resourceAreas/79134c72-4a58-4b42-976c-04e7115f32bf?api-preview=5.0-preview.1) 200 HTTP_2 Local port:  54694
2023-10-27T02:59:23.453-05:00  INFO 3131401 --- [ient-2-Worker-0] jdk.httpclient.HttpClient                : REQUEST: https://dev.azure.com/rabbitearsvideoproduction/_apis/teams?api-version=7.1-preview.3&$skip=0&$top=100&$mine=true&$expandIdentity=true GET
2023-10-27T02:59:23.586-05:00  INFO 3131401 --- [ient-2-Worker-0] jdk.httpclient.HttpClient                : RESPONSE: (GET https://dev.azure.com/rabbitearsvideoproduction/_apis/teams?api-version=7.1-preview.3&$skip=0&$top=100&$mine=true&$expandIdentity=true) 401 HTTP_2 Local port:  54694

For some reason the request is failing with a auth error while get sprints succeed.

2023-10-27T03:01:43.763-05:00  INFO 3131401 --- [ient-2-Worker-2] jdk.httpclient.HttpClient                : REQUEST: https://dev.azure.com/rabbitearsvideoproduction/_apis/resourceAreas/1d4f49f9-02b9-4e26-b826-2cdb6195f2a9?api-preview=5.0-preview.1 GET
2023-10-27T03:01:43.896-05:00  INFO 3131401 --- [ient-2-Worker-2] jdk.httpclient.HttpClient                : RESPONSE: (GET https://dev.azure.com/rabbitearsvideoproduction/_apis/resourceAreas/1d4f49f9-02b9-4e26-b826-2cdb6195f2a9?api-preview=5.0-preview.1) 200 HTTP_2 Local port:  45008
2023-10-27T03:01:43.899-05:00  INFO 3131401 --- [ient-2-Worker-2] jdk.httpclient.HttpClient                : REQUEST: https://dev.azure.com/rabbitearsvideoproduction/Noda-Integration-AzureDevOps-adaptor/Noda-Integration-AzureDevOps-adaptor-TeamA/_apis/work/teamsettings/iterations?api-version=7.1-preview.1 GET
2023-10-27T03:01:44.920-05:00  INFO 3131401 --- [ient-2-Worker-2] jdk.httpclient.HttpClient                : RESPONSE: (GET https://dev.azure.com/rabbitearsvideoproduction/Noda-Integration-AzureDevOps-adaptor/Noda-Integration-AzureDevOps-adaptor-TeamA/_apis/work/teamsettings/iterations?api-version=7.1-preview.1) 200 HTTP_2 Local port:  45008

**Comment by jlong23** [comment]
Thank-you for helping me with my  PaT Authority Mistake.   I was shooting for the standard Least Authority Access route and ran into this.

For the limited access I needed for the bridge I have settled for the following.
![Screenshot from 2023-10-30 13-23-19](https://github.com/hkarthik7/azure-devops-java-sdk/assets/12409196/f52301be-b59d-41b5-9eae-486c76ba1afd)
![Screenshot from 2023-10-30 13-23-58](https://github.com/hkarthik7/azure-devops-java-sdk/assets/12409196/159090f9-9324-41a8-8f26-9bf886b49ec0)

I guess I need the PaT Roles next to the API's...  I tend to do that in my swagger documentation, but MS is a different beast than the Java World.

Thanks again!  I am closing this Issue!
